//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadatakA1_Biblioteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class A1Entities : DbContext
    {
        public A1Entities()
            : base("name=A1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Citalac> Citalacs { get; set; }
        public virtual DbSet<Izdali> Izdalis { get; set; }
        public virtual DbSet<Izdavac> Izdavacs { get; set; }
        public virtual DbSet<Knjiga> Knjigas { get; set; }
        public virtual DbSet<Na_Citanju> Na_Citanju { get; set; }
        public virtual DbSet<Ogranak> Ogranaks { get; set; }
        public virtual DbSet<Primerak> Primeraks { get; set; }
    }
}
