//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadatakA1_Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdali
    {
        public int IzdavacID { get; set; }
        public int KnjigaID { get; set; }
        public Nullable<int> Godina { get; set; }
    
        public virtual Izdavac Izdavac { get; set; }
        public virtual Knjiga Knjiga { get; set; }
    }
}
